name: Create and merge PR for latest Vocabulary and Collections

on:
  workflow_dispatch:
    inputs:
      publisher:
        description: 'Author of this release'     
        required: false
        type: string
      timestamp:
        description: 'Date of this release'     
        required: false
        type: string

jobs:
  create-and-merge-pr:
    uses: openactive/skos-vocabulary-workflows/.github/workflows/create-and-merge-pr.yaml@main
    with:
      publisher: ${{ github.event.inputs.publisher }}
      timestamp: ${{ github.event.inputs.timestamp }}
