name: Validate Vocabulary (and release if on master)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  validate-and-release:
    uses: openactive/skos-vocabulary-workflows/.github/workflows/validate-and-release.yaml@main
